apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: play-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - play.jakubnavratil.cz
      secretName: letsencrypt-play-ingress
  rules:
    - host: play.jakubnavratil.cz
      http:
        paths:
          - backend:
              serviceName: play
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: play
spec:
  ports:
    - port: 80
      targetPort: 2567
  selector:
    app: play
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: play
spec:
  replicas: 1
  # Update pods with rolling update
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: play
  template:
    metadata:
      labels:
        app: play
    spec:
      containers:
        - name: play
          image: registry.livesoft.cz/tictactoe:0.0.1-alpha.1
          ports:
            - containerPort: 2567
          env:
            - name: NODE_ENV
              value: 'production'
      imagePullSecrets:
        - name: registry-cred
